# Telemetry pipeline — build, test, coverage and deployment.
#
#   make            # same as `make help`
#   make quickstart # from an empty machine to a verified running system
#
# Every target is a thin wrapper over a real script or a real `go` command, so
# nothing here is a second source of truth. Run `make help` for the list.

SHELL := /bin/bash

# Overridable: `make deploy TAG=v2`, `make test RACE=off`
TAG        ?= v1.0.0
NAMESPACE  ?= telemetry
RELEASE    ?= telemetry
CLUSTER    ?= telemetry
GO         ?= go
RACE       ?= on
COVDIR     ?= dist/coverage
BIN        ?= dist/bin

# One Go module per component, so `go test ./...` cannot cross between them and
# each component stays independently buildable. The MQ has no dependency on the
# other three.
MODULES := streamer collector messageQueue apiGateway

# The umbrella chart and its subcharts. Linting the umbrella alone does not lint
# the subcharts, and the subcharts are where most of the templates live.
CHART  := helm-charts/telemetry
CHARTS := $(wildcard helm-charts/telemetry/charts/*/)

.DEFAULT_GOAL := help
.PHONY: help
help:
	@echo "telemetry pipeline"
	@echo
	@echo "Test and quality"
	@echo "  make test           run every module's unit tests ($(if $(filter on,$(RACE)),with,-without) -race)"
	@echo "  make coverage       statement coverage per module and combined (brief requirement)"
	@echo "  make coverage-html  per-module HTML coverage reports"
	@echo "  make openapi        generate apiGateway/openapi.json from the code (brief requirement)"
	@echo "  make openapi-check  fail if the committed openapi.json is stale"
	@echo "  make fmt            gofmt -w every module"
	@echo "  make fmt-check      fail if any module needs gofmt"
	@echo "  make vet            go vet every module"
	@echo "  make tidy           go mod tidy every module"
	@echo "  make tidy-check     fail if any go.mod/go.sum is stale"
	@echo "  make helm-lint      helm lint the umbrella chart and all subcharts"
	@echo "  make helm-template  render the chart against values-prod.yaml"
	@echo "  make lint           fmt-check + vet + tidy-check (fast, no tests)"
	@echo "  make check          the full gate: lint + helm-lint + openapi-check + test"
	@echo "  make ci             alias for check"
	@echo
	@echo "Build"
	@echo "  make build          compile all four binaries into $(BIN)"
	@echo "  make images         build the four container images (tag $(TAG))"
	@echo "  make image COMPONENT=messagequeue   build just one"
	@echo "  make load           load those images into the kind node"
	@echo
	@echo "Deploy"
	@echo "  make preflight      check tooling and free disk space before deploying"
	@echo "  make cluster        create the kind cluster + generate dist/values-local.yaml"
	@echo "  make cluster-recreate   delete and recreate the cluster, keeping images"
	@echo "  make secrets        create the auth Secrets (idempotent)"
	@echo "  make secrets-rotate SCOPE=api     rotate one credential"
	@echo "  make deploy         helm upgrade the release into $(NAMESPACE)"
	@echo "  make quickstart     full run: cluster, build, load, deploy, verify"
	@echo "  make down           delete the kind cluster"
	@echo "  make reset          delete the cluster and rebuild everything from scratch"
	@echo
	@echo "Verify (needs a running cluster)"
	@echo "  make verify         end-to-end system verification"
	@echo "  make verify-ha      ClickHouse HA checks (no disruption)"
	@echo "  make verify-ha-failover  also kill a replica and the Keeper leader under load"
	@echo "  make metrics        publish the MQ /metrics endpoints on localhost"
	@echo "  make metrics-status one line per MQ replica"
	@echo "  make metrics-stop   stop publishing them"
	@echo
	@echo "Housekeeping"
	@echo "  make clean          remove $(BIN) and $(COVDIR)"
	@echo '  make distclean      also remove dist/ (regenerated by make cluster)'
	@echo "  make prune          delete dangling Docker images (safe, never volumes)"
	@echo "  make prune-all      delete ALL unused images (needs CONFIRM=yes, no volumes)"
	@echo "  make cleanup        cluster + build output gone; images left alone"
	@echo
	@echo "Variables: TAG=$(TAG) NAMESPACE=$(NAMESPACE) RELEASE=$(RELEASE) RACE=$(RACE)"

# ---------------------------------------------------------------- test + coverage

# `set -e` inside the loop, or `|| exit 1`. A bare `for` loop exits with the
# status of its LAST iteration, so a failure in the first module would be
# reported as success. That bug shipped in the README for a while.
.PHONY: test
test:
	@set -e; for m in $(MODULES); do \
	  echo "==> test $$m"; \
	  if [ "$(RACE)" = "on" ]; then \
	    (cd $$m && $(GO) test ./... -race -count=1) || exit 1; \
	  else \
	    (cd $$m && $(GO) test ./... -count=1) || exit 1; \
	  fi; \
	done
	@echo "all modules passed"

.PHONY: race
race:
	@$(MAKE) test RACE=on

.PHONY: coverage
coverage:
	@mkdir -p $(COVDIR)
	@set -e; total_c=0; total_s=0; \
	for m in $(MODULES); do \
	  echo "==> coverage $$m"; \
	  (cd $$m && $(GO) test ./... -count=1 -coverprofile=../$(COVDIR)/$$m.out >/dev/null) || exit 1; \
	done; \
	echo; \
	printf '%-14s %8s %16s\n' "MODULE" "COVER" "STATEMENTS"; \
	for m in $(MODULES); do \
	  p=$(COVDIR)/$$m.out; \
	  s=$$(awk 'NR>1{t+=$$2}END{print t+0}' $$p); \
	  c=$$(awk 'NR>1 && $$3+0>0 {t+=$$2}END{print t+0}' $$p); \
	  total_c=$$((total_c+c)); total_s=$$((total_s+s)); \
	  pct=$$(awk -v c=$$c -v s=$$s 'BEGIN{printf "%.1f", 100*c/s}'); \
	  printf '%-14s %7s%% %7d/%-8d\n' "$$m" "$$pct" "$$c" "$$s"; \
	done; \
	combined=$$(awk -v c=$$total_c -v s=$$total_s 'BEGIN{printf "%.1f", 100*c/s}'); \
	printf '%-14s %7s%% %7d/%-8d\n' "COMBINED" "$$combined" "$$total_c" "$$total_s"; \
	echo; \
	echo "per-module profiles: $(COVDIR)/*.out"

.PHONY: coverage-html
coverage-html: coverage
	@set -e; for m in $(MODULES); do \
	  (cd $$m && $(GO) tool cover -html=../$(COVDIR)/$$m.out -o ../$(COVDIR)/$$m.html) || exit 1; \
	  echo "  $(COVDIR)/$$m.html"; \
	done

# ------------------------------------------------------------------ openapi

# The brief asks for the spec to be generated, not hand-written, so the command
# that produces it belongs next to the test that proves it is current.
.PHONY: openapi
openapi:
	@cd apiGateway && $(GO) run ./cmd/genopenapi
	@echo "wrote apiGateway/openapi.json"

.PHONY: openapi-check
openapi-check:
	@cd apiGateway && $(GO) run ./cmd/genopenapi -check
	@echo "openapi.json is up to date"

# ------------------------------------------------------------------ fmt + vet

.PHONY: fmt
fmt:
	@set -e; for m in $(MODULES); do (cd $$m && $(GO) fmt ./... >/dev/null) || exit 1; done
	@echo "formatted"

.PHONY: fmt-check
fmt-check:
	@bad=0; for m in $(MODULES); do \
	  out=$$(cd $$m && gofmt -l . ); \
	  if [ -n "$$out" ]; then echo "  $$m needs gofmt:"; echo "$$out" | sed 's/^/    /'; bad=1; fi; \
	done; \
	if [ $$bad -ne 0 ]; then echo "run 'make fmt'"; exit 1; fi; \
	echo "all modules gofmt-clean"

.PHONY: vet
vet:
	@set -e; for m in $(MODULES); do echo "==> vet $$m"; (cd $$m && $(GO) vet ./...) || exit 1; done
	@echo "vet clean"

# ------------------------------------------------------------- helm + modules

# Render against values-prod.yaml, NOT bare defaults: clickhouse.interserver
# .existingSecret is a `required()` guard, so `helm template` on values.yaml
# alone fails by design and would look like a broken chart.
.PHONY: helm-lint
helm-lint:
	@set -e; for c in $(CHART) $(CHARTS); do \
	  echo "==> helm lint $$c"; \
	  helm lint "$$c" >/dev/null || exit 1; \
	done
	@echo "all charts lint clean"

.PHONY: helm-template
helm-template:
	@echo "==> helm template $(CHART) -f values-prod.yaml"
	@helm template $(RELEASE) $(CHART) -n $(NAMESPACE) -f helm-charts/telemetry/values-prod.yaml >/dev/null
	@echo "chart renders cleanly"

.PHONY: tidy
tidy:
	@set -e; for m in $(MODULES); do echo "==> go mod tidy $$m"; (cd $$m && $(GO) mod tidy) || exit 1; done
	@echo "modules tidy"

# Back up before tidying, then restore. `go mod tidy` rewrites files, and a
# check that mutates the tree is worse than no check at all -- it found
# apiGateway labelling a directly-imported dependency as `// indirect`.
.PHONY: tidy-check
tidy-check:
	@tmp=$$(mktemp -d); bad=0; \
	for m in $(MODULES); do \
	  cp $$m/go.mod $$tmp/$$m.mod; cp $$m/go.sum $$tmp/$$m.sum; \
	  (cd $$m && $(GO) mod tidy) >/dev/null 2>&1; \
	  if ! diff -q $$m/go.mod $$tmp/$$m.mod >/dev/null || ! diff -q $$m/go.sum $$tmp/$$m.sum >/dev/null; then \
	    echo "  $$m: go.mod/go.sum is not tidy:"; diff -u $$tmp/$$m.mod $$m/go.mod | sed 's/^/    /' | head -6; bad=1; \
	  fi; \
	  cp $$tmp/$$m.mod $$m/go.mod; cp $$tmp/$$m.sum $$m/go.sum; \
	done; \
	rm -rf $$tmp; \
	if [ $$bad -ne 0 ]; then echo "run 'make tidy' and commit the result"; exit 1; fi; \
	echo "all modules tidy"

# Static only, no tests: seconds, so run it on every edit.
.PHONY: lint
lint: fmt-check vet tidy-check
	@echo "lint: clean"

# The gate. Ordered cheapest-first so an obvious failure surfaces in seconds
# rather than after the two-minute race-enabled test run.
.PHONY: check
check: lint helm-lint openapi-check test
	@echo "check: all green"

.PHONY: ci
ci: check

# ---------------------------------------------------------------------- build

.PHONY: build
build:
	@mkdir -p $(BIN)
	@set -e; \
	(cd streamer     && $(GO) build -o ../$(BIN)/streamer     ./cmd/streamer)     || exit 1; \
	(cd collector    && $(GO) build -o ../$(BIN)/collector    ./cmd/colailector)    || exit 1; \
	(cd messageQueue && $(GO) build -o ../$(BIN)/messagequeue ./cmd/messagequeue) || exit 1; \
	(cd apiGateway   && $(GO) build -o ../$(BIN)/api          ./cmd/api)          || exit 1; \
	echo "binaries in $(BIN)/"

.PHONY: images
images:
	@IMG_TAG=$(TAG) ./scripts/build-images.sh

# One component only, for a fast iteration: make image COMPONENT=collector
.PHONY: image
image:
	@if [ -z "$(COMPONENT)" ]; then echo "usage: make image COMPONENT=streamer|collector|messageQueue|apiGateway"; exit 2; fi
	@IMG_TAG=$(TAG) ./scripts/build-images.sh $(COMPONENT)

.PHONY: load
load:
	@./scripts/load-images.sh $(TAG)

.PHONY: images-save
images-save:
	@./scripts/save-images.sh $(TAG)

# --------------------------------------------------------------------- deploy

# Same check quickstart.sh and kind-up.sh run, on its own. Useful before a long
# build, and it tells you which volume is short when a build dies mysteriously.
.PHONY: preflight
preflight:
	@bash -c 'ROOT=. ; . scripts/lib/preflight.sh ; preflight_disk'
	@command -v docker >/dev/null && docker info >/dev/null 2>&1 && \
	  for t in kind kubectl helm python3 curl; do \
	    command -v $$t >/dev/null || echo "  warn: $$t not installed"; \
	  done; echo "  tools  : ok"

.PHONY: cluster
cluster:
	@./scripts/kind-up.sh --tag $(TAG)

# Cluster only, images kept. `make reset` rebuilds the images too; use this when
# you are iterating on the chart rather than the Go code.
.PHONY: cluster-recreate
cluster-recreate:
	@./scripts/kind-up.sh --recreate --tag $(TAG)

.PHONY: secrets
secrets:
	@./scripts/bootstrap-auth-secrets.sh

# Rotate one credential without touching the others:
#   make secrets-rotate SCOPE=api|mq|clickhouse|interserver|tokenkey
.PHONY: secrets-rotate
secrets-rotate:
	@if [ -z "$(SCOPE)" ]; then echo "usage: make secrets-rotate SCOPE=api|mq|clickhouse|interserver|tokenkey"; exit 2; fi
	@./scripts/bootstrap-auth-secrets.sh --force --only $(SCOPE)

.PHONY: deploy
deploy:
	@# dist/values-local.yaml pins this machine's API server IP for the MQ's
	@# NetworkPolicy. It survives `make down`, so a stale one fails later with an
	@# opaque connection error. Fail here instead, with the fix.
	@test -f dist/values-local.yaml || { \
	  echo "dist/values-local.yaml is missing."; \
	  echo "  run: make cluster      # creates the cluster and generates it"; \
	  exit 1; }
	@kubectl get ns $(NAMESPACE) >/dev/null 2>&1 || { \
	  echo "namespace $(NAMESPACE) does not exist, so there is no reachable cluster."; \
	  echo "  run: make cluster      # or make quickstart for the full path"; \
	  exit 1; }
	@helm upgrade --install $(RELEASE) helm-charts/telemetry \
	  -n $(NAMESPACE) \
	  -f helm-charts/telemetry/values-prod.yaml \
	  -f dist/values-local.yaml \
	  --wait --timeout 10m
	@echo "deployed release $(RELEASE) in $(NAMESPACE)"

.PHONY: quickstart
quickstart:
	@./scripts/quickstart.sh --tag $(TAG)

.PHONY: reset
reset:
	@./scripts/quickstart.sh --recreate --tag $(TAG)

.PHONY: down
down:
	@./scripts/kind-up.sh --down

# --------------------------------------------------------------------- verify

.PHONY: verify
verify:
	@./scripts/verify-deployment.sh

.PHONY: verify-ha
verify-ha:
	@./scripts/verify-clickhouse-ha.sh

.PHONY: verify-ha-failover
verify-ha-failover:
	@./scripts/verify-clickhouse-ha.sh --failover

# -------------------------------------------------------------- observability

.PHONY: metrics
metrics:
	@./scripts/mq-metrics-port.sh start

.PHONY: metrics-status
metrics-status:
	@./scripts/mq-metrics-port.sh status

.PHONY: metrics-stop
metrics-stop:
	@./scripts/mq-metrics-port.sh stop

# -------------------------------------------------------------- housekeeping

.PHONY: clean
clean:
	@rm -rf $(BIN) $(COVDIR)
	@echo "removed $(BIN) and $(COVDIR)"

.PHONY: distclean
distclean: clean
	@rm -rf dist
	@echo "removed dist/ (regenerate with make cluster)"

# Reclaim Docker disk. `make clean` only removes build output on the host; when
# the *Docker volume* is the full one (see `make preflight`), these are what
# actually free space.
#
# `prune` is safe and idempotent: dangling images only, never volumes.
# `prune-all` is aggressive and asks first. Neither touches volumes, because a
# volume can hold ClickHouse data that prune cannot bring back.
.PHONY: prune
prune:
	@echo "==> reclaimable before prune"
	@docker system df 2>/dev/null || echo "  (docker not reachable)"
	@docker image prune -f >/dev/null
	@echo "==> after prune"
	@docker system df 2>/dev/null | awk 'NR>1 && $$4 != "0B" {print "  " $$0}' || true
	@echo "pruned dangling images"

# Destructive. Requires CONFIRM=yes so it cannot be triggered by a stray
# `make prune-all`, and still never removes volumes.
.PHONY: prune-all
prune-all:
	@if [ "$(CONFIRM)" != "yes" ]; then \
	  echo "prune-all removes every image not used by a running container,"; \
	  echo "including the images for the other components, so the next build is"; \
	  echo "much slower. It does NOT remove volumes."; \
	  echo; \
	  echo "  make prune-all CONFIRM=yes"; \
	  echo; \
	  echo "To see what would go: docker system df -a"; \
	  exit 2; \
	fi
	@docker system prune -af >/dev/null
	@echo "pruned all unused images"
	@docker system df 2>/dev/null | awk 'NR>1 {print "  " $$0}'

# Everything this repo created, in one command. The cluster goes first because
# deleting it releases the kind node containers, which is usually the bulk.
.PHONY: cleanup
cleanup:
	@echo "==> tearing down the cluster"
	@./scripts/mq-metrics-port.sh stop 2>/dev/null || true
	@./scripts/kind-up.sh --down 2>/dev/null || true
	@echo "==> removing build output"
	@rm -rf $(BIN) $(COVDIR) dist
	@echo "==> removed: cluster, $(BIN), $(COVDIR), dist/"
	@echo "    Docker images were left alone; reclaim with: make prune"