// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.36.2
// source: proto/mq.proto

package mqpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ReplicaFrame is one replicated mutation, identified by the leader's
// generation number (monotonic per mutation). Types:
//
//	"x" = checkpoint {base + all cursors}  -> followed by a full event replay
//	"a" = append of Event (its log offset is implied by the follower's own log)
//	"c" = commit cursor in a group
//	"t" = retention trim (drop events with offset <= floor)
type ReplicaFrame struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Gen           int64                  `protobuf:"varint,1,opt,name=gen,proto3" json:"gen,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Check         *ReplicaCheckpoint     `protobuf:"bytes,3,opt,name=check,proto3" json:"check,omitempty"`
	Event         *Event                 `protobuf:"bytes,4,opt,name=event,proto3" json:"event,omitempty"`
	Group         string                 `protobuf:"bytes,5,opt,name=group,proto3" json:"group,omitempty"`
	Consumer      string                 `protobuf:"bytes,6,opt,name=consumer,proto3" json:"consumer,omitempty"`
	Offset        int64                  `protobuf:"varint,7,opt,name=offset,proto3" json:"offset,omitempty"` // commit cursor
	Floor         int64                  `protobuf:"varint,8,opt,name=floor,proto3" json:"floor,omitempty"`   // trim barrier
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReplicaFrame) Reset() {
	*x = ReplicaFrame{}
	mi := &file_proto_mq_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReplicaFrame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplicaFrame) ProtoMessage() {}

func (x *ReplicaFrame) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mq_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplicaFrame.ProtoReflect.Descriptor instead.
func (*ReplicaFrame) Descriptor() ([]byte, []int) {
	return file_proto_mq_proto_rawDescGZIP(), []int{0}
}

func (x *ReplicaFrame) GetGen() int64 {
	if x != nil {
		return x.Gen
	}
	return 0
}

func (x *ReplicaFrame) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *ReplicaFrame) GetCheck() *ReplicaCheckpoint {
	if x != nil {
		return x.Check
	}
	return nil
}

func (x *ReplicaFrame) GetEvent() *Event {
	if x != nil {
		return x.Event
	}
	return nil
}

func (x *ReplicaFrame) GetGroup() string {
	if x != nil {
		return x.Group
	}
	return ""
}

func (x *ReplicaFrame) GetConsumer() string {
	if x != nil {
		return x.Consumer
	}
	return ""
}

func (x *ReplicaFrame) GetOffset() int64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *ReplicaFrame) GetFloor() int64 {
	if x != nil {
		return x.Floor
	}
	return 0
}

// ReplicaAck is sent by the follower to the leader. The first message on the
// stream is the hello: resume_log_offset = the follower's current log tail, so
// the leader replays only events the follower does not have yet. Every later
// message acks the last applied gen.
type ReplicaAck struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ResumeLogOffset int64                  `protobuf:"varint,1,opt,name=resume_log_offset,json=resumeLogOffset,proto3" json:"resume_log_offset,omitempty"`
	Gen             int64                  `protobuf:"varint,2,opt,name=gen,proto3" json:"gen,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ReplicaAck) Reset() {
	*x = ReplicaAck{}
	mi := &file_proto_mq_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReplicaAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplicaAck) ProtoMessage() {}

func (x *ReplicaAck) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mq_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplicaAck.ProtoReflect.Descriptor instead.
func (*ReplicaAck) Descriptor() ([]byte, []int) {
	return file_proto_mq_proto_rawDescGZIP(), []int{1}
}

func (x *ReplicaAck) GetResumeLogOffset() int64 {
	if x != nil {
		return x.ResumeLogOffset
	}
	return 0
}

func (x *ReplicaAck) GetGen() int64 {
	if x != nil {
		return x.Gen
	}
	return 0
}

// ReplicaCheckpoint seeds a (re)connecting follower with the leader's absolute
// log base and every durable cursor, so cursors converge even if the follower
// was briefly offline.
type ReplicaCheckpoint struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Base          int64                  `protobuf:"varint,1,opt,name=base,proto3" json:"base,omitempty"`
	Cursors       []*CursorStatus        `protobuf:"bytes,2,rep,name=cursors,proto3" json:"cursors,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReplicaCheckpoint) Reset() {
	*x = ReplicaCheckpoint{}
	mi := &file_proto_mq_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReplicaCheckpoint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplicaCheckpoint) ProtoMessage() {}

func (x *ReplicaCheckpoint) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mq_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplicaCheckpoint.ProtoReflect.Descriptor instead.
func (*ReplicaCheckpoint) Descriptor() ([]byte, []int) {
	return file_proto_mq_proto_rawDescGZIP(), []int{2}
}

func (x *ReplicaCheckpoint) GetBase() int64 {
	if x != nil {
		return x.Base
	}
	return 0
}

func (x *ReplicaCheckpoint) GetCursors() []*CursorStatus {
	if x != nil {
		return x.Cursors
	}
	return nil
}

type CursorStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Group         string                 `protobuf:"bytes,1,opt,name=group,proto3" json:"group,omitempty"`
	Consumer      string                 `protobuf:"bytes,2,opt,name=consumer,proto3" json:"consumer,omitempty"`
	Offset        int64                  `protobuf:"varint,3,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CursorStatus) Reset() {
	*x = CursorStatus{}
	mi := &file_proto_mq_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CursorStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CursorStatus) ProtoMessage() {}

func (x *CursorStatus) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mq_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CursorStatus.ProtoReflect.Descriptor instead.
func (*CursorStatus) Descriptor() ([]byte, []int) {
	return file_proto_mq_proto_rawDescGZIP(), []int{3}
}

func (x *CursorStatus) GetGroup() string {
	if x != nil {
		return x.Group
	}
	return ""
}

func (x *CursorStatus) GetConsumer() string {
	if x != nil {
		return x.Consumer
	}
	return ""
}

func (x *CursorStatus) GetOffset() int64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type JoinPartitionRequest struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	ConsumerId string                 `protobuf:"bytes,1,opt,name=consumer_id,json=consumerId,proto3" json:"consumer_id,omitempty"`
	TtlSeconds int32                  `protobuf:"varint,2,opt,name=ttl_seconds,json=ttlSeconds,proto3" json:"ttl_seconds,omitempty"`
	// group is the fleet namespace this consumer belongs to (e.g. "streamer" or
	// "collector"). Each group owns an independent shard assignment.
	Group         string `protobuf:"bytes,3,opt,name=group,proto3" json:"group,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JoinPartitionRequest) Reset() {
	*x = JoinPartitionRequest{}
	mi := &file_proto_mq_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinPartitionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinPartitionRequest) ProtoMessage() {}

func (x *JoinPartitionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mq_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinPartitionRequest.ProtoReflect.Descriptor instead.
func (*JoinPartitionRequest) Descriptor() ([]byte, []int) {
	return file_proto_mq_proto_rawDescGZIP(), []int{4}
}

func (x *JoinPartitionRequest) GetConsumerId() string {
	if x != nil {
		return x.ConsumerId
	}
	return ""
}

func (x *JoinPartitionRequest) GetTtlSeconds() int32 {
	if x != nil {
		return x.TtlSeconds
	}
	return 0
}

func (x *JoinPartitionRequest) GetGroup() string {
	if x != nil {
		return x.Group
	}
	return ""
}

type JoinPartitionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Index         int32                  `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JoinPartitionResponse) Reset() {
	*x = JoinPartitionResponse{}
	mi := &file_proto_mq_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinPartitionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinPartitionResponse) ProtoMessage() {}

func (x *JoinPartitionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mq_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinPartitionResponse.ProtoReflect.Descriptor instead.
func (*JoinPartitionResponse) Descriptor() ([]byte, []int) {
	return file_proto_mq_proto_rawDescGZIP(), []int{5}
}

func (x *JoinPartitionResponse) GetIndex() int32 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *JoinPartitionResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

type LeavePartitionRequest struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	ConsumerId string                 `protobuf:"bytes,1,opt,name=consumer_id,json=consumerId,proto3" json:"consumer_id,omitempty"`
	// group must match the group used at JoinPartition time.
	Group         string `protobuf:"bytes,2,opt,name=group,proto3" json:"group,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LeavePartitionRequest) Reset() {
	*x = LeavePartitionRequest{}
	mi := &file_proto_mq_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LeavePartitionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeavePartitionRequest) ProtoMessage() {}

func (x *LeavePartitionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mq_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeavePartitionRequest.ProtoReflect.Descriptor instead.
func (*LeavePartitionRequest) Descriptor() ([]byte, []int) {
	return file_proto_mq_proto_rawDescGZIP(), []int{6}
}

func (x *LeavePartitionRequest) GetConsumerId() string {
	if x != nil {
		return x.ConsumerId
	}
	return ""
}

func (x *LeavePartitionRequest) GetGroup() string {
	if x != nil {
		return x.Group
	}
	return ""
}

type LeavePartitionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LeavePartitionResponse) Reset() {
	*x = LeavePartitionResponse{}
	mi := &file_proto_mq_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LeavePartitionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeavePartitionResponse) ProtoMessage() {}

func (x *LeavePartitionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mq_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeavePartitionResponse.ProtoReflect.Descriptor instead.
func (*LeavePartitionResponse) Descriptor() ([]byte, []int) {
	return file_proto_mq_proto_rawDescGZIP(), []int{7}
}

type Event struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	EventId string                 `protobuf:"bytes,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	// The streamer's current UTC time when it produced the event, RFC3339 with
	// nanosecond precision. The CSV's own timestamp column is never used.
	SourceTimestamp string            `protobuf:"bytes,13,opt,name=source_timestamp,json=sourceTimestamp,proto3" json:"source_timestamp,omitempty"`
	MetricName      string            `protobuf:"bytes,3,opt,name=metric_name,json=metricName,proto3" json:"metric_name,omitempty"`
	GpuIndex        int32             `protobuf:"varint,4,opt,name=gpu_index,json=gpuIndex,proto3" json:"gpu_index,omitempty"`
	DeviceName      string            `protobuf:"bytes,5,opt,name=device_name,json=deviceName,proto3" json:"device_name,omitempty"`
	DeviceId        string            `protobuf:"bytes,6,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	ModelName       string            `protobuf:"bytes,7,opt,name=model_name,json=modelName,proto3" json:"model_name,omitempty"`
	Hostname        string            `protobuf:"bytes,8,opt,name=hostname,proto3" json:"hostname,omitempty"`
	Value           float64           `protobuf:"fixed64,9,opt,name=value,proto3" json:"value,omitempty"`
	CsvLineOffset   int64             `protobuf:"varint,10,opt,name=csv_line_offset,json=csvLineOffset,proto3" json:"csv_line_offset,omitempty"`
	LoopCount       int64             `protobuf:"varint,11,opt,name=loop_count,json=loopCount,proto3" json:"loop_count,omitempty"`
	Tags            map[string]string `protobuf:"bytes,12,rep,name=tags,proto3" json:"tags,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Event) Reset() {
	*x = Event{}
	mi := &file_proto_mq_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Event) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event) ProtoMessage() {}

func (x *Event) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mq_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Event.ProtoReflect.Descriptor instead.
func (*Event) Descriptor() ([]byte, []int) {
	return file_proto_mq_proto_rawDescGZIP(), []int{8}
}

func (x *Event) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *Event) GetSourceTimestamp() string {
	if x != nil {
		return x.SourceTimestamp
	}
	return ""
}

func (x *Event) GetMetricName() string {
	if x != nil {
		return x.MetricName
	}
	return ""
}

func (x *Event) GetGpuIndex() int32 {
	if x != nil {
		return x.GpuIndex
	}
	return 0
}

func (x *Event) GetDeviceName() string {
	if x != nil {
		return x.DeviceName
	}
	return ""
}

func (x *Event) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *Event) GetModelName() string {
	if x != nil {
		return x.ModelName
	}
	return ""
}

func (x *Event) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *Event) GetValue() float64 {
	if x != nil {
		return x.Value
	}
	return 0
}

func (x *Event) GetCsvLineOffset() int64 {
	if x != nil {
		return x.CsvLineOffset
	}
	return 0
}

func (x *Event) GetLoopCount() int64 {
	if x != nil {
		return x.LoopCount
	}
	return 0
}

func (x *Event) GetTags() map[string]string {
	if x != nil {
		return x.Tags
	}
	return nil
}

type Ack struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventId       string                 `protobuf:"bytes,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	Offset        int64                  `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	Success       bool                   `protobuf:"varint,3,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Ack) Reset() {
	*x = Ack{}
	mi := &file_proto_mq_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ack) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ack) ProtoMessage() {}

func (x *Ack) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mq_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ack.ProtoReflect.Descriptor instead.
func (*Ack) Descriptor() ([]byte, []int) {
	return file_proto_mq_proto_rawDescGZIP(), []int{9}
}

func (x *Ack) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *Ack) GetOffset() int64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *Ack) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *Ack) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type GetOffsetRequest struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	ConsumerId string                 `protobuf:"bytes,1,opt,name=consumer_id,json=consumerId,proto3" json:"consumer_id,omitempty"`
	// group scoping (see JoinPartitionRequest.group).
	Group         string `protobuf:"bytes,2,opt,name=group,proto3" json:"group,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOffsetRequest) Reset() {
	*x = GetOffsetRequest{}
	mi := &file_proto_mq_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOffsetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOffsetRequest) ProtoMessage() {}

func (x *GetOffsetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mq_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOffsetRequest.ProtoReflect.Descriptor instead.
func (*GetOffsetRequest) Descriptor() ([]byte, []int) {
	return file_proto_mq_proto_rawDescGZIP(), []int{10}
}

func (x *GetOffsetRequest) GetConsumerId() string {
	if x != nil {
		return x.ConsumerId
	}
	return ""
}

func (x *GetOffsetRequest) GetGroup() string {
	if x != nil {
		return x.Group
	}
	return ""
}

type GetOffsetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Offset        int64                  `protobuf:"varint,1,opt,name=offset,proto3" json:"offset,omitempty"`
	Exists        bool                   `protobuf:"varint,2,opt,name=exists,proto3" json:"exists,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOffsetResponse) Reset() {
	*x = GetOffsetResponse{}
	mi := &file_proto_mq_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOffsetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOffsetResponse) ProtoMessage() {}

func (x *GetOffsetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mq_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOffsetResponse.ProtoReflect.Descriptor instead.
func (*GetOffsetResponse) Descriptor() ([]byte, []int) {
	return file_proto_mq_proto_rawDescGZIP(), []int{11}
}

func (x *GetOffsetResponse) GetOffset() int64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *GetOffsetResponse) GetExists() bool {
	if x != nil {
		return x.Exists
	}
	return false
}

// ConsumeRequest: a consumer resumes reading the log from just past
// start_offset. Consumers with a committed cursor pass their last processed
// offset here; a never-committed consumer uses -1 to start at the beginning of
// the retained log. group is informational (cursors live in the collector
// group via CommitOffset).
type ConsumeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ConsumerId    string                 `protobuf:"bytes,1,opt,name=consumer_id,json=consumerId,proto3" json:"consumer_id,omitempty"`
	StartOffset   int64                  `protobuf:"varint,2,opt,name=start_offset,json=startOffset,proto3" json:"start_offset,omitempty"`
	Group         string                 `protobuf:"bytes,3,opt,name=group,proto3" json:"group,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConsumeRequest) Reset() {
	*x = ConsumeRequest{}
	mi := &file_proto_mq_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConsumeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConsumeRequest) ProtoMessage() {}

func (x *ConsumeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mq_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConsumeRequest.ProtoReflect.Descriptor instead.
func (*ConsumeRequest) Descriptor() ([]byte, []int) {
	return file_proto_mq_proto_rawDescGZIP(), []int{12}
}

func (x *ConsumeRequest) GetConsumerId() string {
	if x != nil {
		return x.ConsumerId
	}
	return ""
}

func (x *ConsumeRequest) GetStartOffset() int64 {
	if x != nil {
		return x.StartOffset
	}
	return 0
}

func (x *ConsumeRequest) GetGroup() string {
	if x != nil {
		return x.Group
	}
	return ""
}

// ConsumedEvent pairs an event with its log offset. The offset is what a
// consumer commits back via CommitOffset, and the shard key a sharded fleet
// uses to decide ownership (offset % total == index).
type ConsumedEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Event         *Event                 `protobuf:"bytes,1,opt,name=event,proto3" json:"event,omitempty"`
	Offset        int64                  `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConsumedEvent) Reset() {
	*x = ConsumedEvent{}
	mi := &file_proto_mq_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConsumedEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConsumedEvent) ProtoMessage() {}

func (x *ConsumedEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mq_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConsumedEvent.ProtoReflect.Descriptor instead.
func (*ConsumedEvent) Descriptor() ([]byte, []int) {
	return file_proto_mq_proto_rawDescGZIP(), []int{13}
}

func (x *ConsumedEvent) GetEvent() *Event {
	if x != nil {
		return x.Event
	}
	return nil
}

func (x *ConsumedEvent) GetOffset() int64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type CommitOffsetRequest struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	ConsumerId string                 `protobuf:"bytes,1,opt,name=consumer_id,json=consumerId,proto3" json:"consumer_id,omitempty"`
	Offset     int64                  `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	// group scoping of the committed cursor (see JoinPartitionRequest.group).
	Group         string `protobuf:"bytes,3,opt,name=group,proto3" json:"group,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommitOffsetRequest) Reset() {
	*x = CommitOffsetRequest{}
	mi := &file_proto_mq_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommitOffsetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommitOffsetRequest) ProtoMessage() {}

func (x *CommitOffsetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mq_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommitOffsetRequest.ProtoReflect.Descriptor instead.
func (*CommitOffsetRequest) Descriptor() ([]byte, []int) {
	return file_proto_mq_proto_rawDescGZIP(), []int{14}
}

func (x *CommitOffsetRequest) GetConsumerId() string {
	if x != nil {
		return x.ConsumerId
	}
	return ""
}

func (x *CommitOffsetRequest) GetOffset() int64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *CommitOffsetRequest) GetGroup() string {
	if x != nil {
		return x.Group
	}
	return ""
}

type CommitOffsetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommitOffsetResponse) Reset() {
	*x = CommitOffsetResponse{}
	mi := &file_proto_mq_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommitOffsetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommitOffsetResponse) ProtoMessage() {}

func (x *CommitOffsetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mq_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommitOffsetResponse.ProtoReflect.Descriptor instead.
func (*CommitOffsetResponse) Descriptor() ([]byte, []int) {
	return file_proto_mq_proto_rawDescGZIP(), []int{15}
}

var File_proto_mq_proto protoreflect.FileDescriptor

const file_proto_mq_proto_rawDesc = "" +
	"\n" +
	"\x0eproto/mq.proto\x12\x02mq\"\xe2\x01\n" +
	"\fReplicaFrame\x12\x10\n" +
	"\x03gen\x18\x01 \x01(\x03R\x03gen\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12+\n" +
	"\x05check\x18\x03 \x01(\v2\x15.mq.ReplicaCheckpointR\x05check\x12\x1f\n" +
	"\x05event\x18\x04 \x01(\v2\t.mq.EventR\x05event\x12\x14\n" +
	"\x05group\x18\x05 \x01(\tR\x05group\x12\x1a\n" +
	"\bconsumer\x18\x06 \x01(\tR\bconsumer\x12\x16\n" +
	"\x06offset\x18\a \x01(\x03R\x06offset\x12\x14\n" +
	"\x05floor\x18\b \x01(\x03R\x05floor\"J\n" +
	"\n" +
	"ReplicaAck\x12*\n" +
	"\x11resume_log_offset\x18\x01 \x01(\x03R\x0fresumeLogOffset\x12\x10\n" +
	"\x03gen\x18\x02 \x01(\x03R\x03gen\"S\n" +
	"\x11ReplicaCheckpoint\x12\x12\n" +
	"\x04base\x18\x01 \x01(\x03R\x04base\x12*\n" +
	"\acursors\x18\x02 \x03(\v2\x10.mq.CursorStatusR\acursors\"X\n" +
	"\fCursorStatus\x12\x14\n" +
	"\x05group\x18\x01 \x01(\tR\x05group\x12\x1a\n" +
	"\bconsumer\x18\x02 \x01(\tR\bconsumer\x12\x16\n" +
	"\x06offset\x18\x03 \x01(\x03R\x06offset\"n\n" +
	"\x14JoinPartitionRequest\x12\x1f\n" +
	"\vconsumer_id\x18\x01 \x01(\tR\n" +
	"consumerId\x12\x1f\n" +
	"\vttl_seconds\x18\x02 \x01(\x05R\n" +
	"ttlSeconds\x12\x14\n" +
	"\x05group\x18\x03 \x01(\tR\x05group\"C\n" +
	"\x15JoinPartitionResponse\x12\x14\n" +
	"\x05index\x18\x01 \x01(\x05R\x05index\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\"N\n" +
	"\x15LeavePartitionRequest\x12\x1f\n" +
	"\vconsumer_id\x18\x01 \x01(\tR\n" +
	"consumerId\x12\x14\n" +
	"\x05group\x18\x02 \x01(\tR\x05group\"\x18\n" +
	"\x16LeavePartitionResponse\"\xd4\x03\n" +
	"\x05Event\x12\x19\n" +
	"\bevent_id\x18\x01 \x01(\tR\aeventId\x12)\n" +
	"\x10source_timestamp\x18\r \x01(\tR\x0fsourceTimestamp\x12\x1f\n" +
	"\vmetric_name\x18\x03 \x01(\tR\n" +
	"metricName\x12\x1b\n" +
	"\tgpu_index\x18\x04 \x01(\x05R\bgpuIndex\x12\x1f\n" +
	"\vdevice_name\x18\x05 \x01(\tR\n" +
	"deviceName\x12\x1b\n" +
	"\tdevice_id\x18\x06 \x01(\tR\bdeviceId\x12\x1d\n" +
	"\n" +
	"model_name\x18\a \x01(\tR\tmodelName\x12\x1a\n" +
	"\bhostname\x18\b \x01(\tR\bhostname\x12\x14\n" +
	"\x05value\x18\t \x01(\x01R\x05value\x12&\n" +
	"\x0fcsv_line_offset\x18\n" +
	" \x01(\x03R\rcsvLineOffset\x12\x1d\n" +
	"\n" +
	"loop_count\x18\v \x01(\x03R\tloopCount\x12'\n" +
	"\x04tags\x18\f \x03(\v2\x13.mq.Event.TagsEntryR\x04tags\x1a7\n" +
	"\tTagsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01J\x04\b\x02\x10\x03R\ttimestamp\"h\n" +
	"\x03Ack\x12\x19\n" +
	"\bevent_id\x18\x01 \x01(\tR\aeventId\x12\x16\n" +
	"\x06offset\x18\x02 \x01(\x03R\x06offset\x12\x18\n" +
	"\asuccess\x18\x03 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x04 \x01(\tR\x05error\"I\n" +
	"\x10GetOffsetRequest\x12\x1f\n" +
	"\vconsumer_id\x18\x01 \x01(\tR\n" +
	"consumerId\x12\x14\n" +
	"\x05group\x18\x02 \x01(\tR\x05group\"C\n" +
	"\x11GetOffsetResponse\x12\x16\n" +
	"\x06offset\x18\x01 \x01(\x03R\x06offset\x12\x16\n" +
	"\x06exists\x18\x02 \x01(\bR\x06exists\"j\n" +
	"\x0eConsumeRequest\x12\x1f\n" +
	"\vconsumer_id\x18\x01 \x01(\tR\n" +
	"consumerId\x12!\n" +
	"\fstart_offset\x18\x02 \x01(\x03R\vstartOffset\x12\x14\n" +
	"\x05group\x18\x03 \x01(\tR\x05group\"H\n" +
	"\rConsumedEvent\x12\x1f\n" +
	"\x05event\x18\x01 \x01(\v2\t.mq.EventR\x05event\x12\x16\n" +
	"\x06offset\x18\x02 \x01(\x03R\x06offset\"d\n" +
	"\x13CommitOffsetRequest\x12\x1f\n" +
	"\vconsumer_id\x18\x01 \x01(\tR\n" +
	"consumerId\x12\x16\n" +
	"\x06offset\x18\x02 \x01(\x03R\x06offset\x12\x14\n" +
	"\x05group\x18\x03 \x01(\tR\x05group\"\x16\n" +
	"\x14CommitOffsetResponse2\xf7\x02\n" +
	"\fMessageQueue\x12'\n" +
	"\rPublishEvents\x12\t.mq.Event\x1a\a.mq.Ack(\x010\x01\x128\n" +
	"\tGetOffset\x12\x14.mq.GetOffsetRequest\x1a\x15.mq.GetOffsetResponse\x12D\n" +
	"\rJoinPartition\x12\x18.mq.JoinPartitionRequest\x1a\x19.mq.JoinPartitionResponse\x12G\n" +
	"\x0eLeavePartition\x12\x19.mq.LeavePartitionRequest\x1a\x1a.mq.LeavePartitionResponse\x122\n" +
	"\aConsume\x12\x12.mq.ConsumeRequest\x1a\x11.mq.ConsumedEvent0\x01\x12A\n" +
	"\fCommitOffset\x12\x17.mq.CommitOffsetRequest\x1a\x18.mq.CommitOffsetResponse2;\n" +
	"\vReplication\x12,\n" +
	"\x04Sync\x12\x0e.mq.ReplicaAck\x1a\x10.mq.ReplicaFrame(\x010\x01B\x15Z\x13streamer/proto;mqpbb\x06proto3"

var (
	file_proto_mq_proto_rawDescOnce sync.Once
	file_proto_mq_proto_rawDescData []byte
)

func file_proto_mq_proto_rawDescGZIP() []byte {
	file_proto_mq_proto_rawDescOnce.Do(func() {
		file_proto_mq_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_mq_proto_rawDesc), len(file_proto_mq_proto_rawDesc)))
	})
	return file_proto_mq_proto_rawDescData
}

var file_proto_mq_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_proto_mq_proto_goTypes = []any{
	(*ReplicaFrame)(nil),           // 0: mq.ReplicaFrame
	(*ReplicaAck)(nil),             // 1: mq.ReplicaAck
	(*ReplicaCheckpoint)(nil),      // 2: mq.ReplicaCheckpoint
	(*CursorStatus)(nil),           // 3: mq.CursorStatus
	(*JoinPartitionRequest)(nil),   // 4: mq.JoinPartitionRequest
	(*JoinPartitionResponse)(nil),  // 5: mq.JoinPartitionResponse
	(*LeavePartitionRequest)(nil),  // 6: mq.LeavePartitionRequest
	(*LeavePartitionResponse)(nil), // 7: mq.LeavePartitionResponse
	(*Event)(nil),                  // 8: mq.Event
	(*Ack)(nil),                    // 9: mq.Ack
	(*GetOffsetRequest)(nil),       // 10: mq.GetOffsetRequest
	(*GetOffsetResponse)(nil),      // 11: mq.GetOffsetResponse
	(*ConsumeRequest)(nil),         // 12: mq.ConsumeRequest
	(*ConsumedEvent)(nil),          // 13: mq.ConsumedEvent
	(*CommitOffsetRequest)(nil),    // 14: mq.CommitOffsetRequest
	(*CommitOffsetResponse)(nil),   // 15: mq.CommitOffsetResponse
	nil,                            // 16: mq.Event.TagsEntry
}
var file_proto_mq_proto_depIdxs = []int32{
	2,  // 0: mq.ReplicaFrame.check:type_name -> mq.ReplicaCheckpoint
	8,  // 1: mq.ReplicaFrame.event:type_name -> mq.Event
	3,  // 2: mq.ReplicaCheckpoint.cursors:type_name -> mq.CursorStatus
	16, // 3: mq.Event.tags:type_name -> mq.Event.TagsEntry
	8,  // 4: mq.ConsumedEvent.event:type_name -> mq.Event
	8,  // 5: mq.MessageQueue.PublishEvents:input_type -> mq.Event
	10, // 6: mq.MessageQueue.GetOffset:input_type -> mq.GetOffsetRequest
	4,  // 7: mq.MessageQueue.JoinPartition:input_type -> mq.JoinPartitionRequest
	6,  // 8: mq.MessageQueue.LeavePartition:input_type -> mq.LeavePartitionRequest
	12, // 9: mq.MessageQueue.Consume:input_type -> mq.ConsumeRequest
	14, // 10: mq.MessageQueue.CommitOffset:input_type -> mq.CommitOffsetRequest
	1,  // 11: mq.Replication.Sync:input_type -> mq.ReplicaAck
	9,  // 12: mq.MessageQueue.PublishEvents:output_type -> mq.Ack
	11, // 13: mq.MessageQueue.GetOffset:output_type -> mq.GetOffsetResponse
	5,  // 14: mq.MessageQueue.JoinPartition:output_type -> mq.JoinPartitionResponse
	7,  // 15: mq.MessageQueue.LeavePartition:output_type -> mq.LeavePartitionResponse
	13, // 16: mq.MessageQueue.Consume:output_type -> mq.ConsumedEvent
	15, // 17: mq.MessageQueue.CommitOffset:output_type -> mq.CommitOffsetResponse
	0,  // 18: mq.Replication.Sync:output_type -> mq.ReplicaFrame
	12, // [12:19] is the sub-list for method output_type
	5,  // [5:12] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_proto_mq_proto_init() }
func file_proto_mq_proto_init() {
	if File_proto_mq_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_mq_proto_rawDesc), len(file_proto_mq_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_proto_mq_proto_goTypes,
		DependencyIndexes: file_proto_mq_proto_depIdxs,
		MessageInfos:      file_proto_mq_proto_msgTypes,
	}.Build()
	File_proto_mq_proto = out.File
	file_proto_mq_proto_goTypes = nil
	file_proto_mq_proto_depIdxs = nil
}
