// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v7.36.2
// source: proto/mq.proto

package mqpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	MessageQueue_PublishEvents_FullMethodName  = "/mq.MessageQueue/PublishEvents"
	MessageQueue_GetOffset_FullMethodName      = "/mq.MessageQueue/GetOffset"
	MessageQueue_JoinPartition_FullMethodName  = "/mq.MessageQueue/JoinPartition"
	MessageQueue_LeavePartition_FullMethodName = "/mq.MessageQueue/LeavePartition"
	MessageQueue_Consume_FullMethodName        = "/mq.MessageQueue/Consume"
	MessageQueue_CommitOffset_FullMethodName   = "/mq.MessageQueue/CommitOffset"
)

// MessageQueueClient is the client API for MessageQueue service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// MessageQueue is the contract implemented by the messageQueue service and
// consumed by the streamer. Keeping it here as the source of truth so the
// streamer and MQ can be generated/implemented against the same definition.
type MessageQueueClient interface {
	// PublishEvents is a bidirectional stream: the streamer sends Events and the
	// MQ replies with an Ack per event. Deduplication is done by the MQ keyed on
	// event_id (idempotent producer).
	PublishEvents(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[Event, Ack], error)
	// GetOffset returns the last acknowledged offset for a consumer in a group.
	// Used by the streamer on startup (crash recovery) to resume processing from
	// there. Offsets are group-scoped (see JoinPartitionRequest.group): the
	// streamer group holds the last acked csv_line_offset; the collector group
	// holds the last committed log cursor.
	GetOffset(ctx context.Context, in *GetOffsetRequest, opts ...grpc.CallOption) (*GetOffsetResponse, error)
	// JoinPartition makes the MQ's partition registry aware of a consumer and
	// returns the consumer's assigned index among the currently active set in its
	// group. The MQ orders the live consumers of the group and hands each one a
	// unique 0..total-1 index. Repeated calls act as a heartbeat that keeps the
	// consumer active (dead consumers expire via ttl_seconds, which self-heals
	// scale-downs). The group keeps independent fleets (e.g. "streamer" and
	// "collector") from sharing one shard assignment.
	JoinPartition(ctx context.Context, in *JoinPartitionRequest, opts ...grpc.CallOption) (*JoinPartitionResponse, error)
	// LeavePartition removes a consumer from the registry immediately. Used on
	// graceful shutdown so surviving replicas rebalance without waiting for the
	// heartbeat TTL to expire.
	LeavePartition(ctx context.Context, in *LeavePartitionRequest, opts ...grpc.CallOption) (*LeavePartitionResponse, error)
	// Consume streams the consumer read path of the event log. It returns every
	// event with offset > start_offset, in log order, up to the current end of
	// the log, then closes the stream (the consumer re-invokes from its updated
	// cursor to follow new events). This is the pull-based cursor model that lets
	// consumers recover from crashes: GetOffset/CommitOffset bound where a
	// restarted consumer resumes.
	Consume(ctx context.Context, in *ConsumeRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ConsumedEvent], error)
	// CommitOffset records a consumer's processed position (the highest logged
	// offset fully written downstream). Must only be advanced after the consumer
	// has durably persisted everything up to that offset, so a crash triggers a
	// safe replay (duplicates are absorbed downstream). Committed cursors also
	// advance the MQ's retention barrier for the collector group.
	CommitOffset(ctx context.Context, in *CommitOffsetRequest, opts ...grpc.CallOption) (*CommitOffsetResponse, error)
}

type messageQueueClient struct {
	cc grpc.ClientConnInterface
}

func NewMessageQueueClient(cc grpc.ClientConnInterface) MessageQueueClient {
	return &messageQueueClient{cc}
}

func (c *messageQueueClient) PublishEvents(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[Event, Ack], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &MessageQueue_ServiceDesc.Streams[0], MessageQueue_PublishEvents_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[Event, Ack]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type MessageQueue_PublishEventsClient = grpc.BidiStreamingClient[Event, Ack]

func (c *messageQueueClient) GetOffset(ctx context.Context, in *GetOffsetRequest, opts ...grpc.CallOption) (*GetOffsetResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetOffsetResponse)
	err := c.cc.Invoke(ctx, MessageQueue_GetOffset_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *messageQueueClient) JoinPartition(ctx context.Context, in *JoinPartitionRequest, opts ...grpc.CallOption) (*JoinPartitionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(JoinPartitionResponse)
	err := c.cc.Invoke(ctx, MessageQueue_JoinPartition_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *messageQueueClient) LeavePartition(ctx context.Context, in *LeavePartitionRequest, opts ...grpc.CallOption) (*LeavePartitionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LeavePartitionResponse)
	err := c.cc.Invoke(ctx, MessageQueue_LeavePartition_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *messageQueueClient) Consume(ctx context.Context, in *ConsumeRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ConsumedEvent], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &MessageQueue_ServiceDesc.Streams[1], MessageQueue_Consume_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ConsumeRequest, ConsumedEvent]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type MessageQueue_ConsumeClient = grpc.ServerStreamingClient[ConsumedEvent]

func (c *messageQueueClient) CommitOffset(ctx context.Context, in *CommitOffsetRequest, opts ...grpc.CallOption) (*CommitOffsetResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CommitOffsetResponse)
	err := c.cc.Invoke(ctx, MessageQueue_CommitOffset_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MessageQueueServer is the server API for MessageQueue service.
// All implementations must embed UnimplementedMessageQueueServer
// for forward compatibility.
//
// MessageQueue is the contract implemented by the messageQueue service and
// consumed by the streamer. Keeping it here as the source of truth so the
// streamer and MQ can be generated/implemented against the same definition.
type MessageQueueServer interface {
	// PublishEvents is a bidirectional stream: the streamer sends Events and the
	// MQ replies with an Ack per event. Deduplication is done by the MQ keyed on
	// event_id (idempotent producer).
	PublishEvents(grpc.BidiStreamingServer[Event, Ack]) error
	// GetOffset returns the last acknowledged offset for a consumer in a group.
	// Used by the streamer on startup (crash recovery) to resume processing from
	// there. Offsets are group-scoped (see JoinPartitionRequest.group): the
	// streamer group holds the last acked csv_line_offset; the collector group
	// holds the last committed log cursor.
	GetOffset(context.Context, *GetOffsetRequest) (*GetOffsetResponse, error)
	// JoinPartition makes the MQ's partition registry aware of a consumer and
	// returns the consumer's assigned index among the currently active set in its
	// group. The MQ orders the live consumers of the group and hands each one a
	// unique 0..total-1 index. Repeated calls act as a heartbeat that keeps the
	// consumer active (dead consumers expire via ttl_seconds, which self-heals
	// scale-downs). The group keeps independent fleets (e.g. "streamer" and
	// "collector") from sharing one shard assignment.
	JoinPartition(context.Context, *JoinPartitionRequest) (*JoinPartitionResponse, error)
	// LeavePartition removes a consumer from the registry immediately. Used on
	// graceful shutdown so surviving replicas rebalance without waiting for the
	// heartbeat TTL to expire.
	LeavePartition(context.Context, *LeavePartitionRequest) (*LeavePartitionResponse, error)
	// Consume streams the consumer read path of the event log. It returns every
	// event with offset > start_offset, in log order, up to the current end of
	// the log, then closes the stream (the consumer re-invokes from its updated
	// cursor to follow new events). This is the pull-based cursor model that lets
	// consumers recover from crashes: GetOffset/CommitOffset bound where a
	// restarted consumer resumes.
	Consume(*ConsumeRequest, grpc.ServerStreamingServer[ConsumedEvent]) error
	// CommitOffset records a consumer's processed position (the highest logged
	// offset fully written downstream). Must only be advanced after the consumer
	// has durably persisted everything up to that offset, so a crash triggers a
	// safe replay (duplicates are absorbed downstream). Committed cursors also
	// advance the MQ's retention barrier for the collector group.
	CommitOffset(context.Context, *CommitOffsetRequest) (*CommitOffsetResponse, error)
	mustEmbedUnimplementedMessageQueueServer()
}

// UnimplementedMessageQueueServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMessageQueueServer struct{}

func (UnimplementedMessageQueueServer) PublishEvents(grpc.BidiStreamingServer[Event, Ack]) error {
	return status.Errorf(codes.Unimplemented, "method PublishEvents not implemented")
}
func (UnimplementedMessageQueueServer) GetOffset(context.Context, *GetOffsetRequest) (*GetOffsetResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetOffset not implemented")
}
func (UnimplementedMessageQueueServer) JoinPartition(context.Context, *JoinPartitionRequest) (*JoinPartitionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method JoinPartition not implemented")
}
func (UnimplementedMessageQueueServer) LeavePartition(context.Context, *LeavePartitionRequest) (*LeavePartitionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LeavePartition not implemented")
}
func (UnimplementedMessageQueueServer) Consume(*ConsumeRequest, grpc.ServerStreamingServer[ConsumedEvent]) error {
	return status.Errorf(codes.Unimplemented, "method Consume not implemented")
}
func (UnimplementedMessageQueueServer) CommitOffset(context.Context, *CommitOffsetRequest) (*CommitOffsetResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CommitOffset not implemented")
}
func (UnimplementedMessageQueueServer) mustEmbedUnimplementedMessageQueueServer() {}
func (UnimplementedMessageQueueServer) testEmbeddedByValue()                      {}

// UnsafeMessageQueueServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MessageQueueServer will
// result in compilation errors.
type UnsafeMessageQueueServer interface {
	mustEmbedUnimplementedMessageQueueServer()
}

func RegisterMessageQueueServer(s grpc.ServiceRegistrar, srv MessageQueueServer) {
	// If the following call pancis, it indicates UnimplementedMessageQueueServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MessageQueue_ServiceDesc, srv)
}

func _MessageQueue_PublishEvents_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(MessageQueueServer).PublishEvents(&grpc.GenericServerStream[Event, Ack]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type MessageQueue_PublishEventsServer = grpc.BidiStreamingServer[Event, Ack]

func _MessageQueue_GetOffset_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetOffsetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MessageQueueServer).GetOffset(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MessageQueue_GetOffset_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MessageQueueServer).GetOffset(ctx, req.(*GetOffsetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MessageQueue_JoinPartition_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(JoinPartitionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MessageQueueServer).JoinPartition(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MessageQueue_JoinPartition_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MessageQueueServer).JoinPartition(ctx, req.(*JoinPartitionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MessageQueue_LeavePartition_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LeavePartitionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MessageQueueServer).LeavePartition(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MessageQueue_LeavePartition_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MessageQueueServer).LeavePartition(ctx, req.(*LeavePartitionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MessageQueue_Consume_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ConsumeRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(MessageQueueServer).Consume(m, &grpc.GenericServerStream[ConsumeRequest, ConsumedEvent]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type MessageQueue_ConsumeServer = grpc.ServerStreamingServer[ConsumedEvent]

func _MessageQueue_CommitOffset_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CommitOffsetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MessageQueueServer).CommitOffset(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MessageQueue_CommitOffset_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MessageQueueServer).CommitOffset(ctx, req.(*CommitOffsetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// MessageQueue_ServiceDesc is the grpc.ServiceDesc for MessageQueue service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MessageQueue_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "mq.MessageQueue",
	HandlerType: (*MessageQueueServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetOffset",
			Handler:    _MessageQueue_GetOffset_Handler,
		},
		{
			MethodName: "JoinPartition",
			Handler:    _MessageQueue_JoinPartition_Handler,
		},
		{
			MethodName: "LeavePartition",
			Handler:    _MessageQueue_LeavePartition_Handler,
		},
		{
			MethodName: "CommitOffset",
			Handler:    _MessageQueue_CommitOffset_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "PublishEvents",
			Handler:       _MessageQueue_PublishEvents_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "Consume",
			Handler:       _MessageQueue_Consume_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "proto/mq.proto",
}

const (
	Replication_Sync_FullMethodName = "/mq.Replication/Sync"
)

// ReplicationClient is the client API for Replication service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Replication is the leader<->follower contract. A follower calls Sync; the
// leader replies with a checkpoint followed by the live mutation stream. The
// follower acknowledges each applied frame (gen) so the leader can wait for a
// configurable number of followers before acking a publisher (sync
// replication => an acked event is durable on a quorum => loss-free failover).
type ReplicationClient interface {
	Sync(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ReplicaAck, ReplicaFrame], error)
}

type replicationClient struct {
	cc grpc.ClientConnInterface
}

func NewReplicationClient(cc grpc.ClientConnInterface) ReplicationClient {
	return &replicationClient{cc}
}

func (c *replicationClient) Sync(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ReplicaAck, ReplicaFrame], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Replication_ServiceDesc.Streams[0], Replication_Sync_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ReplicaAck, ReplicaFrame]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Replication_SyncClient = grpc.BidiStreamingClient[ReplicaAck, ReplicaFrame]

// ReplicationServer is the server API for Replication service.
// All implementations must embed UnimplementedReplicationServer
// for forward compatibility.
//
// Replication is the leader<->follower contract. A follower calls Sync; the
// leader replies with a checkpoint followed by the live mutation stream. The
// follower acknowledges each applied frame (gen) so the leader can wait for a
// configurable number of followers before acking a publisher (sync
// replication => an acked event is durable on a quorum => loss-free failover).
type ReplicationServer interface {
	Sync(grpc.BidiStreamingServer[ReplicaAck, ReplicaFrame]) error
	mustEmbedUnimplementedReplicationServer()
}

// UnimplementedReplicationServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedReplicationServer struct{}

func (UnimplementedReplicationServer) Sync(grpc.BidiStreamingServer[ReplicaAck, ReplicaFrame]) error {
	return status.Errorf(codes.Unimplemented, "method Sync not implemented")
}
func (UnimplementedReplicationServer) mustEmbedUnimplementedReplicationServer() {}
func (UnimplementedReplicationServer) testEmbeddedByValue()                     {}

// UnsafeReplicationServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ReplicationServer will
// result in compilation errors.
type UnsafeReplicationServer interface {
	mustEmbedUnimplementedReplicationServer()
}

func RegisterReplicationServer(s grpc.ServiceRegistrar, srv ReplicationServer) {
	// If the following call pancis, it indicates UnimplementedReplicationServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Replication_ServiceDesc, srv)
}

func _Replication_Sync_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ReplicationServer).Sync(&grpc.GenericServerStream[ReplicaAck, ReplicaFrame]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Replication_SyncServer = grpc.BidiStreamingServer[ReplicaAck, ReplicaFrame]

// Replication_ServiceDesc is the grpc.ServiceDesc for Replication service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Replication_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "mq.Replication",
	HandlerType: (*ReplicationServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Sync",
			Handler:       _Replication_Sync_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "proto/mq.proto",
}
