#!/usr/bin/env bash
# Create (or reuse) the kind cluster and generate the machine-local values file.
#
#   scripts/kind-up.sh                 # create if missing, then generate values
#   scripts/kind-up.sh --recreate      # delete and rebuild the cluster
#   scripts/kind-up.sh --tag v1.0.0    # pin this image tag in the generated values
#   scripts/kind-up.sh --down          # delete the cluster and stop
#
# Two things here cannot be hardcoded in the chart, because they differ per
# machine and per Docker install. Both are detected and written to
# dist/values-local.yaml, which you then pass to helm alongside values-prod.yaml:
#
#   1. The API server's real address. On kind the apiserver listens on the
#      control-plane node's bridge IP at 6443, and kube-proxy DNATs the
#      10.96.0.1:443 service IP onto it. kindnet evaluates NetworkPolicy egress
#      against the POST-DNAT destination, so the MQ replicas see port 6443 and
#      are dropped unless a rule allows that exact node IP. Hardcoding
#      172.18.0.2 (as values-prod.yaml once did) works on exactly one machine.
#
#   2. The image tag. Every component is built and loaded locally, so the tag
#      must match what scripts/build-images.sh produced.
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
CLUSTER="${CLUSTER:-telemetry}"
NAMESPACE="${NAMESPACE:-telemetry}"
NODE_IMAGE="${NODE_IMAGE:-kindest/node:v1.31.0}"
WORKERS="${WORKERS:-1}"

# MQ metrics ports, published to the host by extraPortMappings below and set as
# nodePortBase in the generated values. Kept as variables because the two must
# agree: a mapping forwards to a fixed container port, so a nodePort allocated
# anywhere else would be published on a host port nothing forwards to.
MQ_METRICS_PORT_BASE="${MQ_METRICS_PORT_BASE:-30910}"
MQ_METRICS_PORTS="${MQ_METRICS_PORTS:-2}"
RECREATE=0
DOWN=0
TAG="${IMG_TAG:-latest}"

while [ $# -gt 0 ]; do
  case "$1" in
    --recreate) RECREATE=1; shift ;;
    --down)     DOWN=1; shift ;;
    --tag)      [ $# -ge 2 ] || { echo "--tag requires a value" >&2; exit 2; }; TAG="$2"; shift 2 ;;
    --tag=*)    TAG="${1#--tag=}"; shift ;;
    -h|--help)  sed -n '2,22p' "$0"; exit 0 ;;
    *) echo "unknown argument: $1" >&2; exit 2 ;;
  esac
done

for tool in docker kind kubectl helm python3; do
  command -v "$tool" >/dev/null || { echo "required tool not found: $tool" >&2; exit 1; }
done
docker info >/dev/null 2>&1 || { echo "docker is not running (start Docker Desktop)" >&2; exit 1; }

# Refuse early if the Docker volume is nearly full: a kind cluster plus the
# component images needs several GB, and discovering that half-way through a
# build leaves a half-created cluster. Override with MIN_FREE_GB / SKIP_DISK_CHECK.
. "$ROOT/scripts/lib/preflight.sh"
preflight_disk || { echo "not enough disk space; see the suggestions above" >&2; exit 1; }

say() { printf '\n\033[1m==> %s\033[0m\n' "$1"; }

# ---------------------------------------------------------------- teardown
if [ "$DOWN" = 1 ]; then
  say "deleting cluster '$CLUSTER'"
  kind delete cluster --name "$CLUSTER"
  echo "removed. container volumes and ./dist are left alone; delete them by hand if wanted."
  exit 0
fi

cluster_exists() { kind get clusters 2>/dev/null | grep -qx "$CLUSTER"; }

if [ "$RECREATE" = 1 ] && cluster_exists; then
  say "deleting existing cluster '$CLUSTER' (--recreate)"
  kind delete cluster --name "$CLUSTER"
fi

# ------------------------------------------------------------------- create
if cluster_exists; then
  say "reusing existing cluster '$CLUSTER'"
else
  say "creating kind cluster '$CLUSTER' ($WORKERS worker(s), node image $NODE_IMAGE)"
  mkdir -p "$ROOT/dist"
  KIND_CFG="$ROOT/dist/kind-config.yaml"
  {
    echo "# GENERATED by scripts/kind-up.sh -- one control-plane plus $WORKERS worker(s)."
    echo "kind: Cluster"
    echo "apiVersion: kind.x-k8s.io/v1alpha4"
    echo "nodes:"
    echo "  - role: control-plane"
    # Publish the MQ metrics node ports on the host.
    #
    # Without this, http://<node-ip>:30810 is unreachable from the host and the
    # only way to read /metrics is `kubectl port-forward`. That is a Docker
    # Desktop limitation, not a cluster one: the node runs inside the Docker VM
    # and its bridge IP is not routable from macOS. extraPortMappings is the
    # supported way to publish a node port, and it only takes effect at cluster
    # creation, which is why it lives here and not in the Helm chart.
    #
    # The ports must match messagequeue.metrics.nodePortBase in the Helm values
    # below, since a mapping forwards to a fixed container port.
    # The key is emitted once, outside the loop: repeating it would produce a
    # second mapping key and silently keep only the last port.
    echo "    extraPortMappings:"
    i=0
    while [ "$i" -lt "$MQ_METRICS_PORTS" ]; do
      echo "      - containerPort: $((MQ_METRICS_PORT_BASE + i))"
      echo "        hostPort: $((MQ_METRICS_PORT_BASE + i))"
      echo "        protocol: TCP"
      i=$((i + 1))
    done
    i=1
    while [ "$i" -le "$WORKERS" ]; do echo "  - role: worker"; i=$((i + 1)); done
  } > "$KIND_CFG"
  # This can take a minute on a cold Docker cache.
  kind create cluster --name "$CLUSTER" --image "$NODE_IMAGE" --config "$KIND_CFG" --wait 180s
  echo "wrote $KIND_CFG"
fi

kubectl cluster-info --context "kind-$CLUSTER" >/dev/null
kubectl config use-context "kind-$CLUSTER" >/dev/null

# ------------------------------------------------------- detect the apiserver
# The control-plane node's address on the Docker "kind" network, which is where
# the apiserver actually listens.
CP_IP=$(docker inspect "$CLUSTER-control-plane" \
  --format '{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' 2>/dev/null)
if [ -z "$CP_IP" ]; then
  echo "could not read the control-plane IP from docker; is the cluster running?" >&2
  exit 1
fi

# Note: there is deliberately no "is 6443 open on the node?" preflight here. The
# kind node image has no nc and runs dash, which has no /dev/tcp, so such a check
# can only ever fail and train people to ignore warnings. Whether the address is
# actually right is a runtime question, and scripts/verify-deployment.sh answers
# it functionally: it asserts exactly one leader was elected and the leader
# Service has exactly one endpoint. All followers means this CIDR is wrong.

say "generating dist/values-local.yaml"
mkdir -p "$ROOT/dist"
VALUES_OUT="$ROOT/dist/values-local.yaml"
cat > "$VALUES_OUT" <<EOF
# GENERATED by scripts/kind-up.sh -- do not edit by hand.
# Regenerate with:  scripts/kind-up.sh --tag $TAG
#
# Machine-specific values that cannot live in the chart:
#   - the kind API server address, for the MQ leader-election egress policy
#   - the local image tag every component was built with
#
# Pull policy is Never on purpose: there is no registry, so a missing tag must
# fail loudly instead of pulling whatever a registry happens to serve.

messagequeue:
  apiServer:
    ipBlocks:
      - cidr: $CP_IP/32
        port: 6443
  # Publishes /metrics on the host ports mapped above, so queue depth and memory
  # can be watched in a browser or scraped by an external Prometheus instead of
  # through `kubectl port-forward`. Only safe because the node ports are bound
  # to this machine's Docker network.
  metrics:
    enabled: true
    nodePortBase: $MQ_METRICS_PORT_BASE
  image:
    tag: "$TAG"
    pullPolicy: Never

streamer:
  image:
    tag: "$TAG"
    pullPolicy: Never

collector:
  image:
    tag: "$TAG"
    pullPolicy: Never

apigateway:
  image:
    tag: "$TAG"
    pullPolicy: Never
EOF

echo "wrote $VALUES_OUT (apiServer cidr $CP_IP/32, image tag $TAG)"

# -------------------------------------------------------------- namespace
say "ensuring namespace '$NAMESPACE'"
kubectl create namespace "$NAMESPACE" --dry-run=client -o yaml | kubectl apply -f - >/dev/null
kubectl label namespace "$NAMESPACE" kubernetes.io/metadata.name="$NAMESPACE" --overwrite >/dev/null 2>&1 || true
echo "namespace '$NAMESPACE' ready"

cat <<EOF
next (the tag below must be the same one you build and load, or the pods get
ErrImageNeverPull because values-local.yaml asks for an image that was never
built):

  IMG_TAG=$TAG ./scripts/build-images.sh
  ./scripts/load-images.sh $TAG
  ./scripts/bootstrap-auth-secrets.sh
  helm upgrade --install telemetry $ROOT/helm-charts/telemetry -n $NAMESPACE \\
    -f $ROOT/helm-charts/telemetry/values-prod.yaml \\
    -f $VALUES_OUT --wait --timeout 10m

or just run:  ./scripts/quickstart.sh --tag $TAG
EOF